### ISSUE TITLE
Dependencies have been renamed and no longer map correctly 

### ISSUE THREAD

**Issue by rsproule** [worldcoin/world-id-starter#19]
`worldcoin/world-id-example-airdrop` does not exist.

[Line](https://github.com/worldcoin/world-id-starter/blob/main/.gitmodules#L4-L6
)
``` 
[submodule "lib/world-id-example-airdrop"]
	path = lib/world-id-example-airdrop
	url = https://github.com/worldcoin/world-id-example-airdrop
```

**Comment by rsproule** [comment]
This airdrop repo no longer exists. Should probably be getting this stuff from `world-id-contracts` but the interfaces are all changed/renamed over there in newer versions.

**Comment by m1guelpf** [comment]
Repo has been recreated, this should be fixed now :)
